<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import type { ApiClient } from './api.js';
  import type { PluginTab } from './router.js';
  import { asApiError, isAbortError, type ApiErrorLike, type Commit, type PluginDetail, type PluginVersion, type RepositoryBlob, type RepositoryRefs, type RepositoryTree } from './types.js';
  export let apiClient: ApiClient; export let namespace: string; export let plugin: string; export let tab: PluginTab='code'; export let path='';
  let detail: PluginDetail | null = null, refs: RepositoryRefs={branches:[],tags:[],defaultRef:''}, selectedRef='', tree: RepositoryTree | null = null, blob: RepositoryBlob | null = null, commits: Commit[]=[], versions: PluginVersion[]=[], state: 'loading'|'ready'|'error'='loading', error: ApiErrorLike | null = null, pending='', publishTag='', makeDefault=false, visibility='public', controller: AbortController | undefined;
  $: base=`/plugins/${encodeURIComponent(namespace)}/${encodeURIComponent(plugin)}`;
  onMount(load); onDestroy(()=>controller?.abort());
  async function load(){controller?.abort();controller=new AbortController();state='loading';error=null;try{detail=await apiClient.getPlugin(namespace,plugin,{signal:controller.signal});visibility=detail.visibility;if(tab==='code'){refs=await apiClient.listRepositoryRefs(namespace,plugin,{signal:controller.signal});selectedRef=selectedRef||refs.defaultRef||refs.branches[0]?.name||refs.tags[0]?.name||'';if(selectedRef)await loadCode();}else if(tab==='commits'){refs=await apiClient.listRepositoryRefs(namespace,plugin,{signal:controller.signal});selectedRef=selectedRef||refs.defaultRef||refs.branches[0]?.name||'';if(selectedRef){const result=await apiClient.listRepositoryCommits(namespace,plugin,selectedRef,path,1,100,{signal:controller.signal});commits=result.items;}}else if(tab==='versions'){const result=await apiClient.listPluginVersions(namespace,plugin,1,100,{signal:controller.signal});versions=result.items;}state='ready';}catch(cause){if(!isAbortError(cause)){error=asApiError(cause);state='error';}}}
  let latest: Commit | undefined, historyError = '', copying = '';
  selectedRef = new URLSearchParams(window.location.search).get('ref') || '';
  $: segments = path.split('/').filter(Boolean);
  $: lines = blob ? blob.content.replace(/\n$/, '').split('\n') : [];
  function codeLink(next = '', ref = selectedRef) { return `${base}/code${next ? '/' + next.split('/').map(encodeURIComponent).join('/') : ''}?ref=${encodeURIComponent(ref)}`; }
  async function loadCode(){error=null;blob=null;tree=null;latest=undefined;historyError='';try{if(path){try{blob=await apiClient.getRepositoryBlob(namespace,plugin,selectedRef,path,{signal:controller?.signal});}catch(cause){const apiError=asApiError(cause);if(apiError.status!==409&&apiError.status!==422)throw cause;tree=await apiClient.getRepositoryTree(namespace,plugin,selectedRef,path,{signal:controller?.signal});}}else tree=await apiClient.getRepositoryTree(namespace,plugin,selectedRef,'',{signal:controller?.signal});}catch(cause){if(!isAbortError(cause))error=asApiError(cause);}
    try { const result = await apiClient.listRepositoryCommits(namespace,plugin,selectedRef,path,1,1,{signal:controller?.signal}); latest=result.items[0]; } catch(cause) { if(!isAbortError(cause))historyError='Recent commit unavailable.'; }
  }
  function changeRef(){window.history.pushState({},'',codeLink());window.dispatchEvent(new PopStateEvent('popstate'));}
  async function copyClone(){try{await navigator.clipboard.writeText(new URL(detail?.cloneUrl ?? '',location.origin).href);copying='Copied!';}catch{copying='Copy unavailable. Select and copy the URL below.';}}
  async function publish(event: SubmitEvent){event.preventDefault();pending='publish';error=null;try{await apiClient.publishPluginVersion(namespace,plugin,{tag:publishTag,makeDefault});publishTag='';makeDefault=false;await load();}catch(cause){error=asApiError(cause);}finally{pending='';}}
  async function setDefault(tag: string){pending=tag;try{await apiClient.setDefaultPluginVersion(namespace,plugin,tag);await load();}catch(cause){error=asApiError(cause);}finally{pending='';}}
  async function saveVisibility(){pending='visibility';try{await apiClient.setPluginVisibility(namespace,plugin,visibility);await load();}catch(cause){error=asApiError(cause);}finally{pending='';}}
  async function toggleArchive(){if(!detail)return;pending='archive';try{if(detail.status==='archived')await apiClient.restorePlugin(namespace,plugin);else await apiClient.archivePlugin(namespace,plugin);await load();}catch(cause){error=asApiError(cause);}finally{pending='';}}
</script>
<svelte:head><title>{namespace} / {plugin} · MarketplaceServer</title></svelte:head>
<section class="page repository-page"><header class="repo-header"><div class="page-header"><h1 class="repo-title"><svg class="repo-icon" aria-hidden="true" viewBox="0 0 16 16"><path d="M3 1.5h9v13H3a1.5 1.5 0 0 1-1.5-1.5v-10A1.5 1.5 0 0 1 3 1.5Z M2 11h10 M5 4h4 M5 6h4"/></svg><a data-route href="/plugins">{namespace}</a><span class="muted">/</span><a data-route href={codeLink('', selectedRef || refs.defaultRef)}><strong>{plugin}</strong></a>{#if detail}<span class="status">{detail.visibility}</span>{/if}</h1></div><nav class="repo-tabs" aria-label="Plugin project"><a data-route href={codeLink('', selectedRef || refs.defaultRef)} aria-current={tab==='code'||tab==='commits'?'page':undefined}><span aria-hidden="true">&lt;&gt;</span> Code</a><a data-route href={`${base}/versions`} aria-current={tab==='versions'?'page':undefined}>Versions</a><a data-route href={`${base}/settings`} aria-current={tab==='settings'?'page':undefined}>Settings</a></nav></header>{#if state==='loading'}<p class="panel" role="status">Loading project…</p>{:else if state==='error'}<div class="panel" role="alert"><p class="error">{error?.message}</p><button class="secondary" onclick={load}>Retry</button></div>{:else}{#if error}<p class="panel error" role="alert">{error.message}</p>{/if}{#if tab==='code'}
  <div class="repository-layout" class:file-layout={Boolean(blob)}><div class="repository-main">
    <div class="code-toolbar">
      <select class="field branch-select" id="code-ref" aria-label="Branch or tag" bind:value={selectedRef} onchange={changeRef} disabled={!selectedRef}>
        {#if !selectedRef}<option value="">No branches</option>{/if}
        {#if refs.branches.length}<optgroup label="Branches">{#each refs.branches as ref}<option value={ref.name}>{ref.name}</option>{/each}</optgroup>{/if}
        {#if refs.tags.length}<optgroup label="Tags">{#each refs.tags as ref}<option value={ref.name}>{ref.name}</option>{/each}</optgroup>{/if}
      </select>
      <nav class="breadcrumbs" aria-label="File path"><a data-route href={codeLink()}>{plugin}</a>{#each segments as segment, index}<span class="muted">/</span>{#if index===segments.length-1}<strong>{segment}</strong>{:else}<a data-route href={codeLink(segments.slice(0,index+1).join('/'))}>{segment}</a>{/if}{/each}</nav>
      <details class="clone-menu"><summary class="primary">Clone</summary><div class="clone-popover"><h2>Clone this repository</h2><p class="muted">Use the URL below with your Git client.</p><input class="field" aria-label="Clone URL" readonly value={detail ? new URL(detail.cloneUrl,location.origin).href : ''}/><button class="secondary" onclick={copyClone}>Copy clone URL</button>{#if copying}<p role="status">{copying}</p>{/if}</div></details>
    </div>
    {#if !selectedRef}<div class="panel empty-repository"><h2>Quick setup</h2><p>This repository is empty. Clone it, add your Plugin files, commit, and push.</p>{#if detail?.cloneUrl}<pre class="code-view">git clone {detail.cloneUrl}</pre>{/if}</div>
    {:else}
      <div class="repo-browser">
        <div class="commit-summary">{#if latest}<strong>{latest.authorName}</strong><span class="commit-subject">{latest.subject}</span><code>{latest.sha.slice(0,7)}</code><time class="muted" datetime={latest.committedAt}>{new Date(latest.committedAt).toLocaleDateString()}</time>{:else}<span class="muted">{historyError || 'No commits.'}</span>{/if}<a class="history-link" data-route href={`${base}/commits${path?'/'+segments.map(encodeURIComponent).join('/'):''}?ref=${encodeURIComponent(selectedRef)}`}>History</a></div>
        {#if tree}<table class="file-table" aria-label="Repository files"><thead class="sr-only"><tr><th>Name</th><th>Last commit</th><th>Size</th></tr></thead><tbody>
          {#if path}<tr><td colspan="3"><a data-route href={codeLink(segments.slice(0,-1).join('/'))} aria-label="Parent directory">..</a></td></tr>{/if}
          {#each tree.entries as entry}<tr><td><span class="file-name"><svg class="file-icon" class:folder-icon={entry.type==='tree'} aria-hidden="true" viewBox="0 0 16 16">{#if entry.type==='tree'}<path d="M1.5 3h5l1.5 2h6.5v8h-13Z"/>{:else}<path d="M3.5 1.5h6l3 3v10h-9Z M9.5 1.5v3h3"/>{/if}</svg><a data-route href={codeLink(path?`${path}/${entry.name}`:entry.name)}>{entry.name}</a></span></td><td class="muted">{entry.lastCommit?.message || ''}</td><td class="muted">{typeof entry.size==='number'?`${entry.size} B`:''}</td></tr>{/each}
          {#if !tree.entries.length}<tr><td colspan="3" class="muted">This directory is empty.</td></tr>{/if}
        </tbody></table>
        {:else if blob}<div class="blob-toolbar"><strong>{segments.at(-1)}</strong><span class="muted">{lines.length} lines · {blob.size} bytes</span>{#if blob.commitSha}<code>{blob.commitSha.slice(0,12)}</code>{/if}</div><div class="source-scroll" role="region" aria-label="File source"><table class="source-lines"><tbody>{#each lines as line, index}<tr id={`L${index+1}`}><td class="line-number"><a href={`#L${index+1}`} aria-label={`Line ${index+1}`}>{index+1}</a></td><td class="source-line"><code>{line || ' '}</code></td></tr>{/each}</tbody></table></div>{/if}
      </div>
    {/if}
  </div>
  {#if !blob}<aside class="repo-about" aria-label="About"><h2>About</h2><p class="muted">Claude Code Plugin</p><dl><dt>Visibility</dt><dd>{detail?.visibility}</dd><dt>Status</dt><dd>{detail?.status}</dd></dl><div class="about-section"><h2><a data-route href={`${base}/versions`}>Versions</a></h2>{#if detail?.defaultVersion}<a class="version-link" data-route href={`${base}/versions`}>{detail.defaultVersion}</a><span class="status">Default</span>{:else}<p class="muted">No default version selected.</p>{/if}</div></aside>{/if}
  </div>
{:else if tab==='commits'}<section><div class="repo-toolbar"><select class="field compact" id="commit-ref" aria-label="Branch or tag" bind:value={selectedRef} onchange={load}>{#each refs.branches as ref}<option value={ref.name}>{ref.name}</option>{/each}{#each refs.tags as ref}<option value={ref.name}>{ref.name}</option>{/each}</select><span class="muted">History {path?`for ${path}`:''}</span></div>{#if !commits.length}<p class="panel muted">No commits.</p>{:else}<ul class="plain-list">{#each commits as commit}<li class="row"><div><strong>{commit.subject}</strong><p class="muted">{commit.authorName} committed {new Date(commit.committedAt).toLocaleString()}</p></div><code>{commit.sha.slice(0,12)}</code></li>{/each}</ul>{/if}</section>{:else if tab==='versions'}<form class="panel form-inline" onsubmit={publish}><h2>Publish canonical tag</h2><label for="publish-tag">Tag</label><input class="field" id="publish-tag" required pattern="v.*" placeholder="v1.0.0" bind:value={publishTag}/><label for="make-default">Default version</label><input id="make-default" type="checkbox" bind:checked={makeDefault}/><button class="primary" disabled={Boolean(pending)}>{pending==='publish'?'Publishing…':'Publish version'}</button></form>{#if !versions.length}<p class="panel muted">No published versions.</p>{:else}<ul class="plain-list">{#each versions as version}<li class="row"><div><strong>{version.tag}</strong> <span class="status">{version.status}</span><p class="muted"><code>{version.commitSha.slice(0,12)}</code> · published {new Date(version.publishedAt).toLocaleString()}</p></div>{#if detail?.defaultVersion===version.tag}<strong>Default</strong>{:else if version.status==='available'}<button class="secondary" disabled={Boolean(pending)} onclick={()=>setDefault(version.tag)}>Set default</button>{/if}</li>{/each}</ul>{/if}{:else if tab==='settings' && detail}<form class="panel form-inline" onsubmit={(event: SubmitEvent)=>{event.preventDefault();saveVisibility();}}><h2>Visibility</h2><label for="visibility">Plugin visibility</label><select class="field" id="visibility" bind:value={visibility}><option value="public">Public</option><option value="private">Private</option></select><button class="primary" disabled={Boolean(pending)}>{pending==='visibility'?'Saving…':'Save visibility'}</button></form><section class="panel"><h2>Archive Plugin</h2><p class="muted">Archived Plugins retain repository content and can be restored.</p><button class="danger" disabled={Boolean(pending)} onclick={toggleArchive}>{detail.status==='archived'?'Restore Plugin':'Archive Plugin'}</button></section>{/if}{/if}</section>
