<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import type { ApiClient } from './api.js';
  import { asApiError, isAbortError, type ApiErrorLike, type Plugin, type Team, type UserProfile } from './types.js';
  export let apiClient: ApiClient; export let profile: UserProfile | null = null;
  let namespace='', teams: Team[]=[], items: Plugin[]=[], state: 'loading'|'ready'|'error'='loading', error: ApiErrorLike | null = null, pending=false, name='', visibility='public', controller: AbortController | undefined;
  $: choices = profile ? [{ slug: profile.username, displayName: profile.displayName || profile.username }, ...teams] : teams;
  onMount(initialize); onDestroy(()=>controller?.abort());
  async function initialize(){controller?.abort();controller=new AbortController();state='loading';error=null;try{const result=await apiClient.listTeams(1,100,'',{signal:controller.signal});teams=result.items;if(!namespace)namespace=profile?.username||teams[0]?.slug||'';await load();}catch(e){if(!isAbortError(e)){error=asApiError(e);state='error';}}}
  async function load(){if(!namespace)return;controller?.abort();controller=new AbortController();state='loading';error=null;try{const result=await apiClient.listPlugins(namespace,1,100,{signal:controller.signal});items=result.items;state='ready';}catch(e){if(!isAbortError(e)){error=asApiError(e);state='error';}}}
  async function create(event: SubmitEvent){event.preventDefault();pending=true;error=null;try{await apiClient.createPlugin(namespace,{name,visibility});name='';visibility='public';await load();}catch(e){error=asApiError(e);}finally{pending=false;}}
</script>
<svelte:head><title>Plugins · MarketplaceServer</title></svelte:head>
<section class="page">
  <header class="page-header"><div><p class="eyebrow">Projects</p><h1>Plugins</h1><p class="muted">Host source, review code, and publish canonical versions.</p></div><label for="plugin-namespace">Namespace <select class="field compact" id="plugin-namespace" bind:value={namespace} onchange={load}>{#each choices as choice}<option value={choice.slug}>{choice.displayName} ({choice.slug})</option>{/each}</select></label></header>
  <form class="panel form-inline" onsubmit={create}><h2>Create a new Plugin</h2><label for="plugin-name">Plugin name</label><input class="field" id="plugin-name" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" bind:value={name}/><label for="plugin-visibility">Visibility</label><select class="field" id="plugin-visibility" bind:value={visibility}><option value="public">Public</option><option value="private">Private</option></select>{#if error}<p class="error" role="alert">{error.status===409?'That Plugin name already exists in this namespace.':error.message}</p>{/if}<button class="primary" disabled={pending||!namespace}>{pending?'Creating…':'Create Plugin'}</button></form>
  {#if state==='loading'}<p class="panel" role="status">Loading Plugins…</p>{:else if state==='error'}<div class="panel" role="alert"><p class="error">{error?.message}</p><button class="secondary" onclick={load}>Retry</button></div>{:else if !items.length}<div class="panel"><h2>No Plugins in {namespace}</h2><p class="muted">Create one to provision its hidden Git repository.</p></div>{:else}<ul class="card-list">{#each items as item (item.name)}<li class="panel row"><div><h2><a data-route href={`/plugins/${encodeURIComponent(item.namespace)}/${encodeURIComponent(item.name)}`}>{item.namespace} / {item.name}</a></h2><p class="muted">{item.visibility} · {item.status} · repository {item.repositoryStatus}{item.defaultVersion?` · default ${item.defaultVersion}`:''}</p></div><a class="secondary" data-route href={`/plugins/${encodeURIComponent(item.namespace)}/${encodeURIComponent(item.name)}`}>Open project</a></li>{/each}</ul>{/if}
</section>
