<script>
  import { onDestroy, onMount } from 'svelte';
  export let apiClient; export let namespace; export let plugin; export let tab='code'; export let path='';
  let detail, refs={branches:[],tags:[],defaultRef:''}, selectedRef='', tree, blob, commits=[], versions=[], state='loading', error, pending='', publishTag='', makeDefault=false, visibility='public', controller;
  $: base=`/plugins/${encodeURIComponent(namespace)}/${encodeURIComponent(plugin)}`;
  onMount(load); onDestroy(()=>controller?.abort());
  async function load(){controller?.abort();controller=new AbortController();state='loading';error=null;try{detail=await apiClient.getPlugin(namespace,plugin,{signal:controller.signal});visibility=detail.visibility;if(tab==='code'){refs=await apiClient.listRepositoryRefs(namespace,plugin,{signal:controller.signal});selectedRef=selectedRef||refs.defaultRef||refs.branches?.[0]?.name||refs.tags?.[0]?.name||'';if(selectedRef)await loadCode();}else if(tab==='commits'){refs=await apiClient.listRepositoryRefs(namespace,plugin,{signal:controller.signal});selectedRef=selectedRef||refs.defaultRef||refs.branches?.[0]?.name||'';if(selectedRef){const r=await apiClient.listRepositoryCommits(namespace,plugin,selectedRef,path,1,100,{signal:controller.signal});commits=r.items;}}else if(tab==='versions'){const r=await apiClient.listPluginVersions(namespace,plugin,1,100,{signal:controller.signal});versions=r.items;}state='ready';}catch(e){if(e.name!=='AbortError'){error=e;state='error';}}}
  async function loadCode(){error=null;blob=null;tree=null;try{if(path){try{blob=await apiClient.getRepositoryBlob(namespace,plugin,selectedRef,path,{signal:controller.signal});}catch(e){if(e.status!==409&&e.status!==422)throw e;tree=await apiClient.getRepositoryTree(namespace,plugin,selectedRef,path,{signal:controller.signal});}}else tree=await apiClient.getRepositoryTree(namespace,plugin,selectedRef,'',{signal:controller.signal});}catch(e){error=e;}}
  async function changeRef(){path='';window.history.replaceState({},'',`${base}/code`);await loadCode();}
  function openEntry(entry){const next=path?`${path}/${entry.name}`:entry.name;window.history.pushState({},'',`${base}/code/${next.split('/').map(encodeURIComponent).join('/')}`);window.dispatchEvent(new PopStateEvent('popstate'));}
  async function publish(event){event.preventDefault();pending='publish';error=null;try{await apiClient.publishPluginVersion(namespace,plugin,{tag:publishTag,makeDefault});publishTag='';makeDefault=false;await load();}catch(e){error=e;}finally{pending='';}}
  async function setDefault(tag){pending=tag;try{await apiClient.setDefaultPluginVersion(namespace,plugin,tag);await load();}catch(e){error=e;}finally{pending='';}}
  async function saveVisibility(){pending='visibility';try{await apiClient.setPluginVisibility(namespace,plugin,visibility);await load();}catch(e){error=e;}finally{pending='';}}
  async function toggleArchive(){pending='archive';try{detail.status==='archived'?await apiClient.restorePlugin(namespace,plugin):await apiClient.archivePlugin(namespace,plugin);await load();}catch(e){error=e;}finally{pending='';}}
</script>
<svelte:head><title>{namespace} / {plugin} · MarketplaceServer</title></svelte:head>
<section class="page">
  <header class="repo-header"><div class="page-header"><div><p class="eyebrow">Plugin project</p><h1 class="repo-title"><a data-route href="/plugins">{namespace}</a><span class="muted">/</span><strong>{plugin}</strong>{#if detail}<span class="status">{detail.visibility}</span>{/if}</h1></div>{#if detail}<div class="actions"><code>{detail.cloneUrl}</code><button class="secondary" onclick={()=>navigator.clipboard.writeText(new URL(detail.cloneUrl,location.origin).href)}>Copy clone URL</button></div>{/if}</div>
  <nav class="repo-tabs" aria-label="Plugin project"><a data-route href={`${base}/code`} aria-current={tab==='code'?'page':undefined}>Code</a><a data-route href={`${base}/commits`} aria-current={tab==='commits'?'page':undefined}>Commits</a><a data-route href={`${base}/versions`} aria-current={tab==='versions'?'page':undefined}>Versions</a><a data-route href={`${base}/settings`} aria-current={tab==='settings'?'page':undefined}>Settings</a></nav></header>
  {#if state==='loading'}<p class="panel" role="status">Loading project…</p>{:else if state==='error'}<div class="panel" role="alert"><p class="error">{error.message}</p><button class="secondary" onclick={load}>Retry</button></div>{:else}
    {#if error}<p class="panel error" role="alert">{error.message}</p>{/if}
    {#if tab==='code'}<div class="repo-browser"><div class="repo-toolbar"><select class="field compact" id="code-ref" aria-label="Branch or tag" bind:value={selectedRef} onchange={changeRef}>{#if refs.branches?.length}<optgroup label="Branches">{#each refs.branches as ref}<option value={ref.name}>{ref.name}</option>{/each}</optgroup>{/if}{#if refs.tags?.length}<optgroup label="Tags">{#each refs.tags as ref}<option value={ref.name}>{ref.name}</option>{/each}</optgroup>{/if}</select><span class="muted">{path||'/'}</span></div>{#if !selectedRef}<div class="panel"><h2>Quick setup</h2><p>This repository is empty. Clone it, add your Plugin files, commit, and push.</p><pre class="code-view">git clone {detail.cloneUrl}</pre></div>{:else if tree}<div>{#each tree.entries as entry}<button class="repo-row" onclick={()=>openEntry(entry)}><strong>{entry.type==='tree'?'Directory':'File'} · {entry.name}</strong><span class="muted">{entry.lastCommit?.message||''}</span><span class="muted">{entry.size??''}</span></button>{/each}</div>{:else if blob}<div><div class="repo-toolbar"><strong>{blob.path}</strong><span>{blob.size} bytes · {blob.commitSha?.slice(0,12)}</span></div><pre class="code-view">{blob.content}</pre></div>{/if}</div>
    {:else if tab==='commits'}<section><div class="repo-toolbar"><select class="field compact" id="commit-ref" aria-label="Branch or tag" bind:value={selectedRef} onchange={load}>{#each refs.branches||[] as ref}<option value={ref.name}>{ref.name}</option>{/each}{#each refs.tags||[] as ref}<option value={ref.name}>{ref.name}</option>{/each}</select><span class="muted">History {path?`for ${path}`:''}</span></div>{#if !commits.length}<p class="panel muted">No commits.</p>{:else}<ul class="plain-list">{#each commits as commit}<li class="row"><div><strong>{commit.subject}</strong><p class="muted">{commit.authorName} committed {new Date(commit.committedAt).toLocaleString()}</p></div><code>{commit.sha.slice(0,12)}</code></li>{/each}</ul>{/if}</section>
    {:else if tab==='versions'}<form class="panel form-inline" onsubmit={publish}><h2>Publish canonical tag</h2><label for="publish-tag">Tag</label><input class="field" id="publish-tag" required pattern="v.*" placeholder="v1.0.0" bind:value={publishTag}/><label for="make-default">Default version</label><input id="make-default" type="checkbox" bind:checked={makeDefault}/><button class="primary" disabled={pending}>{pending==='publish'?'Publishing…':'Publish version'}</button></form>{#if !versions.length}<p class="panel muted">No published versions.</p>{:else}<ul class="plain-list">{#each versions as version}<li class="row"><div><strong>{version.tag}</strong> <span class="status">{version.status}</span><p class="muted"><code>{version.commitSha.slice(0,12)}</code> · published {new Date(version.publishedAt).toLocaleString()}</p></div>{#if detail.defaultVersion===version.tag}<strong>Default</strong>{:else if version.status==='available'}<button class="secondary" disabled={pending} onclick={()=>setDefault(version.tag)}>Set default</button>{/if}</li>{/each}</ul>{/if}
    {:else if tab==='settings'}<form class="panel form-inline" onsubmit={(e)=>{e.preventDefault();saveVisibility();}}><h2>Visibility</h2><label for="visibility">Plugin visibility</label><select class="field" id="visibility" bind:value={visibility}><option value="public">Public</option><option value="private">Private</option></select><button class="primary" disabled={pending}>{pending==='visibility'?'Saving…':'Save visibility'}</button></form><section class="panel"><h2>Archive Plugin</h2><p class="muted">Archived Plugins retain repository content and can be restored.</p><button class="danger" disabled={pending} onclick={toggleArchive}>{detail.status==='archived'?'Restore Plugin':'Archive Plugin'}</button></section>{/if}
  {/if}
</section>
