<script>
  import { onDestroy, onMount } from 'svelte';
  export let apiClient; export let slug;
  let state='loading', error, team, members=[], invitations=[], controller, pending='', confirm=null, inviteUsername='', inviteRole='viewer', memberUserId='', memberRole='viewer', displayName='';
  onMount(load); onDestroy(()=>controller?.abort());
  async function load(){controller?.abort();controller=new AbortController();state='loading';error=null;try{team=await apiClient.getTeam(slug,{signal:controller.signal});displayName=team.displayName;const jobs=[];if(team.permissions?.readMembers)jobs.push(apiClient.listMembers(slug,1,100,{signal:controller.signal}).then(r=>members=r.items));if(team.permissions?.manageMembers)jobs.push(apiClient.listTeamInvitations(slug,1,100,{signal:controller.signal}).then(r=>invitations=r.items));await Promise.all(jobs);state='ready';}catch(e){if(e.name!=='AbortError'){error=e;state='error';}}}
  async function update(event){event.preventDefault();pending='settings';try{team=await apiClient.updateTeam(slug,{displayName});}catch(e){error=e;}finally{pending='';}}
  async function invite(event){event.preventDefault();pending='invite';error=null;try{await apiClient.invite(slug,{username:inviteUsername,role:inviteRole});inviteUsername='';await load();}catch(e){error=e;}finally{pending='';}}
  async function putMember(event){event.preventDefault();pending='member';error=null;try{await apiClient.putMember(slug,memberUserId,memberRole);memberUserId='';await load();}catch(e){error=e;}finally{pending='';}}
  async function remove(){const item=confirm;confirm=null;pending=item.userId;error=null;try{await apiClient.removeMember(slug,item.userId);await load();}catch(e){error=e;}finally{pending='';}}
</script>
<svelte:head><title>{team?.displayName || slug} · MarketplaceServer</title></svelte:head>
<div class="page">{#if state==='loading'}<p class="panel" role="status">Loading team…</p>{:else if state==='error'}<div class="panel" role="alert"><p class="error">{error.message}</p><button class="secondary" onclick={load}>Retry</button></div>{:else}
<header class="page-header"><div><p class="eyebrow">Team</p><h1>{team.displayName}</h1><p class="muted">{team.slug}{team.currentUserRole?` · ${team.currentUserRole}`:''}</p></div></header>
{#if error}<p class="panel error" role="alert">{error.status===409?'The requested change conflicts with current team state.':error.message}</p>{/if}
{#if team.permissions?.updateSettings}<form class="panel form-inline" onsubmit={update}><h2>Settings</h2><label for="team-display">Display name</label><input class="field" id="team-display" required bind:value={displayName}/><button class="primary" disabled={pending}>{pending==='settings'?'Saving…':'Save'}</button></form>{/if}
{#if team.permissions?.manageMembers}<form class="panel form-inline" onsubmit={invite}><h2>Invite member</h2><label for="invite-user">Username</label><input class="field" id="invite-user" required bind:value={inviteUsername}/><label for="invite-role">Role</label><select class="field" id="invite-role" bind:value={inviteRole}><option value="viewer">Viewer</option><option value="developer">Developer</option><option value="maintainer">Maintainer</option><option value="admin">Admin</option>{#if team.permissions?.manageOwners}<option value="owner">Owner</option>{/if}</select><button class="primary" disabled={pending}>{pending==='invite'?'Inviting…':'Send invitation'}</button></form><form class="panel form-inline" onsubmit={putMember}><h2>Add or update member</h2><label for="member-user-id">User ID</label><input class="field" id="member-user-id" required bind:value={memberUserId}/><label for="member-role">Role</label><select class="field" id="member-role" bind:value={memberRole}><option value="viewer">Viewer</option><option value="developer">Developer</option><option value="maintainer">Maintainer</option><option value="admin">Admin</option>{#if team.permissions?.manageOwners}<option value="owner">Owner</option>{/if}</select><button class="primary" disabled={pending}>{pending==='member'?'Saving…':'Add or update'}</button></form>{/if}
{#if team.permissions?.readMembers}<section class="panel"><h2>Members</h2>{#if !members.length}<p class="muted">No members.</p>{:else}<ul class="plain-list">{#each members as member}<li class="row"><span>{member.displayName||member.username} <span class="muted">· {member.role}</span></span>{#if team.permissions?.manageMembers}<button class="danger" onclick={()=>confirm=member}>Remove</button>{/if}</li>{/each}</ul>{/if}</section>{/if}
{#if team.permissions?.manageMembers}<section class="panel"><h2>Invitations</h2>{#if !invitations.length}<p class="muted">No invitations.</p>{:else}<ul class="plain-list">{#each invitations as invitation}<li class="row"><span>{invitation.username} · {invitation.role} · {invitation.status}</span>{#if invitation.status === 'pending'}<span class="actions"><button class="secondary" disabled={pending} onclick={async()=>{pending=invitation.id;error=null;try{await apiClient.reissueInvitation(slug,invitation.id);await load();}catch(e){error=e;}finally{pending='';}}}>Reissue</button><button class="danger" disabled={pending} onclick={async()=>{pending=invitation.id;error=null;try{await apiClient.revokeInvitation(slug,invitation.id);await load();}catch(e){error=e;}finally{pending='';}}}>Revoke</button></span>{/if}</li>{/each}</ul>{/if}</section>{/if}
{#if confirm}<div class="dialog-backdrop"><dialog class="dialog" open aria-labelledby="confirm-title"><h2 id="confirm-title">Remove team member?</h2><p>This can remove their team access. Final-owner rules may prevent it.</p><div class="actions"><button class="danger" onclick={remove}>Confirm remove</button><button class="secondary" onclick={()=>confirm=null}>Cancel</button></div></dialog></div>{/if}{/if}</div>
